### ISSUE TITLE
pressing a button to reload session data?

### ISSUE THREAD

**Issue by royantar0311** [Tanmoytkd/LeetCode-Session-Tracker#2]
we can fetch the new session data without the user having to press the button if he has not loaded session data in last 30 mins on load of the popup page? that would be a great user experience I think.

**Comment by Tanmoytkd** [comment]
The session data is auto-updated every 60 seconds. This functionality is written in [service-worker.js](https://github.com/Tanmoytkd/LeetCode-Session-Tracker/blob/main/service-worker.js)
