### ISSUE TITLE
Auto reload stops working completely if PC gets disconnected for just 1 minute

### ISSUE THREAD

**Issue by arnobakd** [Tanmoytkd/LeetCode-Session-Tracker#4]
### Issue: 
I have been using this extension for a while now. But I've noticed an issue. If my computer is disconnected from the internet for just 1 minute, the auto reload stops working completely. It doesn't start working until I restart chrome. Can you please take a look at it? 

### Possible solution: 
I think replacing `setInterval` with `chrome.alarms` might fix the issue. But I'm not sure yet.

**Comment by Tanmoytkd** [comment]
Thanks for reporting the issue and the possible solution. I will take a look at that.
